## 統計量を求める
データの分布を表す

In [1]:
import numpy as np

In [3]:
std_norm = np.random.randn(5,5)
std_norm

array([[ 0.20853091, -0.30083504, -0.8744135 ,  0.34572885,  0.08422363],
       [ 0.43030096, -1.7506378 , -0.50691528, -0.32343239, -1.62911365],
       [ 0.91404092,  0.62276599, -1.14158446,  0.67349208,  2.57149359],
       [-1.09446267, -0.40991214,  0.98326737,  0.96502468,  0.29349168],
       [ 0.67487329,  0.43934904, -0.43254993,  0.15574007, -0.81994624]])

In [6]:
std_norm.max()

2.571493588870084

In [7]:
np.max(std_norm)

2.571493588870084

In [8]:
std_norm.min()

-1.7506378032641152

In [11]:
## 最大値のインデックスを取得
std_norm.argmax()

14

In [12]:
## flattenは２次元配列を配列にする
std_norm.flatten()[14]

2.571493588870084

In [17]:
# 中央値　vs 平均値
import time
a = np.random.randn(1000,1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print("median took {} sec".format(after_median-before))
print("mean took {} sec".format(after_mean-after_median))

median took 0.014385700225830078 sec
mean took 0.0006909370422363281 sec


In [19]:
# 標準偏差
np.std(np.random.randn(1000,1000))

1.0008556064745333

In [24]:
std_norm.max(axis=0) # 列毎

array([0.91404092, 0.62276599, 0.98326737, 0.96502468, 2.57149359])

In [23]:
std_norm.max(axis=1) #行毎

array([0.34572885, 0.43030096, 2.57149359, 0.98326737, 0.67487329])