## NumPy Arrays(ndarray)

In [2]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
type(matrix[0][0])

numpy.int64

In [22]:
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)
type(matrix2[0][0])

numpy.complex128

In [16]:
ndarray = np.array([1,2,3],dtype=np.uint8) # unsigned integer 8bit
ndarray

array([1, 2, 3], dtype=uint8)

In [18]:
ndarray = np.array([1,2,3],dtype=np.float32)
ndarray

array([1., 2., 3.], dtype=float32)

In [20]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print(array2)
array1 + array2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
array1 = np.array([[1,2,3]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print(array2)
array1 + array2
# Broadcastingを行なってくれる
# Broadcasting:要素が一致しなくても、自動で補ってくれる

[[1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [32]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
# range関数と同じ使い方
# 3以上１５未満、２毎の数のnp.arrayを作成できる
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [10]:
# ０〜１０までの値を5個抽出する
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [3]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [4]:
10 ** 0.3333

2.1542693374042363