## NumPy Arrays(ndarray)

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
type(matrix[0][0])

numpy.int64

In [22]:
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)
type(matrix2[0][0])

numpy.complex128

In [16]:
ndarray = np.array([1,2,3],dtype=np.uint8) # unsigned integer 8bit
ndarray

array([1, 2, 3], dtype=uint8)

In [18]:
ndarray = np.array([1,2,3],dtype=np.float32)
ndarray

array([1., 2., 3.], dtype=float32)

In [20]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print(array2)
array1 + array2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
array1 = np.array([[1,2,3]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print(array2)
array1 + array2
# Broadcastingを行なってくれる
# Broadcasting:要素が一致しなくても、自動で補ってくれる

[[1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [32]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])