## NumPy Arrays(ndarray)

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
type(matrix[0][0])

numpy.int64

In [9]:
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)

In [10]:
type(matrix2[0][0])

numpy.complex128

In [16]:
ndarray = np.array([1,2,3],dtype=np.uint8) # unsigned integer 8bit
ndarray

array([1, 2, 3], dtype=uint8)

In [18]:
ndarray = np.array([1,2,3],dtype=np.float32)
ndarray

array([1., 2., 3.], dtype=float32)