In [1]:
import numpy as np

In [2]:
ndarray = np.array([1,2,3,4])

In [3]:
ndarray[-1]

4

In [6]:
ndarray = np.array([[1,2],[3,4],[5,6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
print(ndarray[0])
print(ndarray[0][1])
print(ndarray[0,1])

[1 2]
2
2


In [17]:
ndarray = np.array([1,2,3,4])
# 1以上３未満
print(ndarray[1:3])
# 3未満
print(ndarray[:3])
# １以上
print(ndarray[1:])
# 後ろから二つ目以上
print(ndarray[-2:])
# 全て
print(ndarray[:])

[2 3]
[1 2 3]
[2 3 4]
[3 4]
[1 2 3 4]


In [26]:
ndarray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(ndarray)
print(ndarray[:3])
# [行,列,奥行き]
print(ndarray[:3,2:])
print(ndarray[:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
