In [28]:
import numpy as np

In [3]:
# 平方根　square root
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [7]:
# log(Logarithm) 指数を求める時に使用する
x = np.linspace(1,10,10)
np.log(x)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [9]:
# 指数関数  Exponentinal function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [10]:
# ネイピア数
np.e

2.718281828459045

In [11]:
# 合計
array = np.arange(1,11)
np.sum(array)

55

In [14]:
ndarray = array.reshape(2,5)
np.sum(ndarray,axis=1)

array([15, 40])

In [20]:
# 絶対値
array = np.arange(-10,0)
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## その他の便利関数

In [22]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#３より小さいものは３にして７より大きいものは７にする
np.clip(array,3,7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [25]:
1e-4

0.0001

In [26]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# TrueのものはaにFalseのものはbに置き換える。
a = 0
b = 1
np.where(array > 3 , a , b )

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [31]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [34]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [37]:
ndarray = array.reshape(2,5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [38]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
(ndarray > 3).all()

False

In [42]:
#全てTrue？　axisも使用できる
(ndarray > -1).all()

True

In [43]:
#一つでもTrue？　axisも使用できる
(ndarray > 3).any()

True

In [45]:
array = np.array([1,1,1,2,3,3,4,5,6,6,6,6,7,7,7,8])
np.unique(array)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.unique(array,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([3, 1, 2, 1, 1, 4, 3, 1]))

In [48]:
# それぞれの値がいくつあるかをカウントしてくれる。
# 下の例だと0は0,1は3
np.bincount(array)

array([0, 3, 1, 2, 1, 1, 4, 3, 1])

In [49]:
ndarray_even = np.arange(0,18,2).reshape(3,3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [51]:
ndarray_odd = np.arange(1,19,2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [53]:
# axisも使用できる
np.concatenate([ndarray_even,ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [58]:
np.stack([ndarray_even,ndarray_odd],axis = -1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [59]:
stacked_array = _

In [60]:
stacked_array.shape

(3, 3, 2)

In [63]:
ndarray = np.random.randn(3,4)
ndarray

array([[ 0.33335403,  0.61326203, -1.18569014, -0.29623747],
       [-1.44752352, -0.67370446,  0.73080148, -0.65602131],
       [-0.29806459, -0.98949501,  0.75618393, -0.07643216]])

In [64]:
ndarray.shape

(3, 4)

In [65]:
np.transpose(ndarray)

array([[ 0.33335403, -1.44752352, -0.29806459],
       [ 0.61326203, -0.67370446, -0.98949501],
       [-1.18569014,  0.73080148,  0.75618393],
       [-0.29623747, -0.65602131, -0.07643216]])

In [66]:
transpose_ndarray = _

In [67]:
ndarray.T

array([[ 0.33335403, -1.44752352, -0.29806459],
       [ 0.61326203, -0.67370446, -0.98949501],
       [-1.18569014,  0.73080148,  0.75618393],
       [-0.29623747, -0.65602131, -0.07643216]])

In [70]:
ndarray = np.random.randn(3,4,5)
ndarray.shape

(3, 4, 5)

In [71]:
np.save("sample_ndarray",ndarray)

In [74]:
loaded_ndarray = np.load("sample_ndarray.npy")
loaded_ndarray.shape

(3, 4, 5)

In [76]:
dictionary = {
    "id" : 123456,
    "image" : ndarray
}

In [77]:
dictionary

{'id': 123456,
 'image': array([[[ 0.09190113, -0.06003837, -0.00895337,  0.50126448,
           0.25298016],
         [-0.29491825, -0.90318795,  1.8205819 ,  0.01091922,
          -1.1871565 ],
         [ 0.95668967,  0.29715204, -2.00040852,  0.26902347,
          -0.5644189 ],
         [ 1.20051568,  2.68502023, -0.21539161, -0.23694931,
          -1.19321067]],
 
        [[ 0.66405263,  0.36933431, -0.36188217, -1.56668333,
           0.88582143],
         [ 1.24520659, -1.11213393, -0.45829579, -0.4672041 ,
          -0.18400538],
         [ 1.0234325 , -0.13681303, -1.7903584 , -2.11299371,
          -0.60115609],
         [ 0.40756137, -1.37072562, -1.20481715, -0.57863382,
           0.41375389]],
 
        [[ 0.84706663,  0.16329734,  0.8331551 , -0.83969473,
           0.27730651],
         [-1.23772148, -1.52727829,  0.90981194, -0.86334786,
           1.38845518],
         [-0.07583476, -0.69440161, -0.51576505, -1.86339967,
           0.27895473],
         [ 0.67132295, -

In [79]:
np.save("sampledict",dictionary)

In [85]:
loaded_dict = np.load("sampledict.npy", allow_pickle= True)
# dictionaryをarrayに変換するときは[()]を呼ぶ
loaded_dict[()]

{'id': 123456,
 'image': array([[[ 0.09190113, -0.06003837, -0.00895337,  0.50126448,
           0.25298016],
         [-0.29491825, -0.90318795,  1.8205819 ,  0.01091922,
          -1.1871565 ],
         [ 0.95668967,  0.29715204, -2.00040852,  0.26902347,
          -0.5644189 ],
         [ 1.20051568,  2.68502023, -0.21539161, -0.23694931,
          -1.19321067]],
 
        [[ 0.66405263,  0.36933431, -0.36188217, -1.56668333,
           0.88582143],
         [ 1.24520659, -1.11213393, -0.45829579, -0.4672041 ,
          -0.18400538],
         [ 1.0234325 , -0.13681303, -1.7903584 , -2.11299371,
          -0.60115609],
         [ 0.40756137, -1.37072562, -1.20481715, -0.57863382,
           0.41375389]],
 
        [[ 0.84706663,  0.16329734,  0.8331551 , -0.83969473,
           0.27730651],
         [-1.23772148, -1.52727829,  0.90981194, -0.86334786,
           1.38845518],
         [-0.07583476, -0.69440161, -0.51576505, -1.86339967,
           0.27895473],
         [ 0.67132295, -