## 乱数生成

In [2]:
import numpy as np

In [5]:
## 擬似乱数
np.random.rand(3,4)

array([[0.33323512, 0.078953  , 0.36960323, 0.6815481 ],
       [0.62139814, 0.80222388, 0.36124336, 0.6834408 ],
       [0.5724254 , 0.56443104, 0.37026345, 0.61333012]])

In [12]:
## np.random.seedを使用することで、ランダム関数を使用したときに同じ数値を取得できる。そのため、ランダムの数値に再現性を持たせることができる。
## numpyの中ではセルないのみ
np.random.seed(1)
np.random.rand(1)

array([0.417022])

In [18]:
## 標準正規分布からランダムの値を一つ取得する
np.random.randn(3,4)

array([[-0.4531686 ,  0.60415364,  2.38520581, -0.12388333],
       [-0.32419367,  0.31075423,  2.46162831, -0.31612369],
       [-1.81506277,  0.6842495 ,  0.03203253,  0.19627021]])

In [23]:
np.random.normal(0,1)

1.1841713099238866

In [27]:
## np.random.randint()
np.random.randint(10,100,(2,3))

array([[49, 45, 91],
       [38, 32, 48]])

In [29]:
np.random.randint(10)

9

In [30]:
a = [1,2,3]
np.random.choice(a)

3