## Shape

In [1]:
import numpy as np

In [4]:
array1 = np.array([[1,2],[3,4],[5,6]])

In [5]:
array1.shape

(3, 2)

In [6]:
array1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array2 = np.array([1,2,3])
array2.shape

(3,)

In [13]:
np.expand_dims(array2,axis=0)

array([[1, 2, 3]])

In [15]:
np.expand_dims(array2,axis=-1)

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(np.expand_dims(array2,axis=-1))

array([1, 2, 3])

In [17]:
array2

array([1, 2, 3])